# Generated by Django 5.0.6 on 2024-07-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('data_scientist', 'Data Scientist'), ('marketing_staff', 'Marketing Staff')], max_length=20),
        ),
    ]
