# Generated by Django 5.0.6 on 2024-07-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GROUPE_OFFRE', models.IntegerField()),
                ('MNT_FORF_DATA_W0', models.FloatField()),
                ('MNT_TRANSFERT_IN_M4', models.FloatField()),
                ('MNT_TRANSFERT_OUT_M4', models.FloatField()),
                ('MNT_RECHARGE_SUP5_W6', models.FloatField()),
                ('MNT_FORF_DATA_W1', models.FloatField()),
                ('MNT_FORF_DATA_W2', models.FloatField()),
                ('MNT_FORF_DATA_W3', models.FloatField()),
                ('MNT_FORF_DATA_W4', models.FloatField()),
                ('MNT_FORF_DATA_W5', models.FloatField()),
                ('MNT_FORF_DATA_W6', models.FloatField()),
                ('MNT_FORF_DATA_W7', models.FloatField()),
                ('MNT_FORF_DATA_W8', models.FloatField()),
                ('MNT_FORF_DATA_W9', models.FloatField()),
                ('NB_FORF_DATA_W9', models.IntegerField()),
                ('USG_REVENUE_AMT_SMS_W9', models.FloatField()),
                ('NB_APPEL_M4_y', models.IntegerField()),
                ('USG', models.FloatField()),
                ('REVENU', models.FloatField()),
                ('HANDSET', models.FloatField()),
                ('MNT', models.FloatField()),
                ('GROUPE', models.FloatField()),
                ('NB', models.FloatField()),
                ('VOLUME', models.FloatField()),
                ('DURATION', models.FloatField()),
                ('NUM', models.FloatField()),
                ('DUREE', models.FloatField()),
            ],
        ),
    ]
