# Generated by Django 5.0.6 on 2024-07-11 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0005_defaultmodel_modeloption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeloption',
            name='model_file',
            field=models.FileField(upload_to='models'),
        ),
    ]
